name: othello
description: Jogo Othello - Multiplayer  - Sockets
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3
  
dependencies:
  flutter:
    sdk: flutter
  
  bloc: ^8.1.4
  flutter_bloc: ^8.1.3
  window_manager: ^0.3.8
  network_info_plus: ^4.1.0+1
  windows_single_instance: ^1.0.1
  protobuf: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/swords.png

  fonts:
    - family: Press Start 2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
    - family: Roboto Mono
      fonts:
        - asset: assets/fonts/RobotoMono-VariableFont_wght.ttf
